" Show line numbers in grey
set number
highlight LineNr ctermfg=Grey
set cursorline
highlight clear CursorLine
highlight CursorLineNr cterm=bold

" Enable syntax highlighting
syntax on

" Enable X11 clipboard
set clipboard^=unnamedplus

" Enable mouse support
set mouse=a

" Automatically continue comment lines
set formatoptions^=cro

" Map jj and jk to escape in insert and replace modes
inoremap jj <Esc>
inoremap jk <Esc>

" See :help fo-table for explanation
set fo+=1

" Disallow overwriting clipboard with empty region
set cpoptions+=E

" Allow backspacing over autoindent, line breaks, and start of insert
set backspace=indent,eol,start

set foldmethod=marker

" Allow filetype-specific plugins and indenting
filetype plugin indent on

" Use vim-surround keymappings for vim-sandwich
" https://github.com/machakann/vim-sandwich/wiki/Introduce-vim-surround-keymappings
" https://github.com/machakann/vim-sandwich/wiki/Bracket-with-spaces
runtime START macros/sandwich/keymap/surround.vim
let g:sandwich#recipes += [
	\ {
	\	'buns': ['{ ', ' }'], 'nesting': 1, 'match_syntax': 1,
	\	'kind': ['add', 'replace'], 'action': ['add'], 'input': ['{']
	\ },
	\ {
	\	'buns': ['[ ', ' ]'], 'nesting': 1, 'match_syntax': 1,
	\	'kind': ['add', 'replace'], 'action': ['add'], 'input': ['[']
	\ },
	\ {
	\	'buns': ['( ', ' )'], 'nesting': 1, 'match_syntax': 1,
	\	'kind': ['add', 'replace'], 'action': ['add'], 'input': ['(']
	\ },
	\ {
	\	'buns': ['{\s*', '\s*}'], 'nesting': 1, 'regex': 1, 'match_syntax': 1,
	\	'kind': ['delete', 'replace', 'textobj'], 'action': ['delete'],
	\	'input': ['{']
	\ },
	\ {
	\	'buns': ['\[\s*', '\s*\]'], 'nesting': 1, 'regex': 1, 'match_syntax': 1,
	\	'kind': ['delete', 'replace', 'textobj'], 'action': ['delete'],
	\	'input': ['[']
	\ },
	\ {
	\	'buns': ['(\s*', '\s*)'],   'nesting': 1, 'regex': 1, 'match_syntax': 1,
	\	'kind': ['delete', 'replace', 'textobj'], 'action': ['delete'],
	\	'input': ['(']
	\ },
	\ ]

" Mappings for vim-sandwich textobjects
xmap is <Plug>(textobj-sandwich-query-i)
xmap as <Plug>(textobj-sandwich-query-a)
omap is <Plug>(textobj-sandwich-query-i)
omap as <Plug>(textobj-sandwich-query-a)

xmap iss <Plug>(textobj-sandwich-auto-i)
xmap ass <Plug>(textobj-sandwich-auto-a)
omap iss <Plug>(textobj-sandwich-auto-i)
omap ass <Plug>(textobj-sandwich-auto-a)

xmap im <Plug>(textobj-sandwich-literal-query-i)
xmap am <Plug>(textobj-sandwich-literal-query-a)
omap im <Plug>(textobj-sandwich-literal-query-i)
omap am <Plug>(textobj-sandwich-literal-query-a)

" Interpret .tex files as LaTeX by default
let g:tex_flavor='latex'

" Use Zathura to view PDF files
let g:vimtex_view_method='zathura'

" Do not indent on ampersands (this mixes tabs and spaces for alignment, which
" is bad)
let g:vimtex_indent_on_ampersands=0
