" Show line numbers in grey
set number
highlight LineNr ctermfg=Grey
set cursorline
highlight CursorLine none
highlight CursorLineNr cterm=bold

" Enable syntax highlighting
syntax on

" Enable X11 clipboard
set clipboard^=unnamedplus

" Enable mouse support
set mouse=a

" Automatically continue comment lines
set formatoptions^=cro

" Map jj and jk to escape in insert and replace modes
inoremap jj <Esc>
inoremap jk <Esc>

" Allow backspacing over autoindent, line breaks, and start of insert
set backspace=indent,eol,start

" Allow filetype-specific plugins and indenting
filetype plugin indent on

" Interpret .tex files as LaTeX by default
let g:tex_flavor='latex'
" Compile to PDF instead of DVI
let g:Tex_DefaultTargetFormat='pdf'
