#!/usr/bin/env perl
# Copyright 2021 psvenk

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;
use 5.032;

chomp (my @pkgs = `$ENV{HOME}/bin/aurcheck`);

unless (@pkgs) {
	print "AUR: up to date\n";
	print "AUR: 0\n";
	print "#00ff00\n";
	system('notify-send', '-i', 'system-software-update', 'AUR updates',
		'All up to date'
	) if defined $ENV{BLOCK_BUTTON};
	exit;
}

if (@pkgs == 1) {
	print "AUR: 1 update\n";
	print "AUR: 1\n";
} else {
	print "AUR: " . @pkgs . " updates\n";
	print "AUR: " . @pkgs . "\n";
}

print "#ff8000\n";
system('notify-send', '-i', 'system-software-update', 'AUR updates',
	join("\n", @pkgs)
) if defined $ENV{BLOCK_BUTTON};
