#!/bin/sh
# Copyright 2020 psvenk

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

pkgs="$(pacman -Qm | aur vercmp | grep -vf "$XDG_CONFIG_HOME"/aurcheck/ignore)"
numpkgs="$(printf "%s\n" "$pkgs" | wc -l)"

if [ -z "$pkgs" ]
then
	echo "AUR: up to date"
	echo "AUR: 0"
	echo "#00ff00"
	if [ -n "$BLOCK_BUTTON" ]
	then
		notify-send -i "system-software-update" "AUR updates" \
		"All up to date"
	fi
	exit
elif [ "$numpkgs" -eq 1 ]
then
	printf "AUR: 1 update\n"
	printf "AUR: 1\n"
else
	printf "AUR: %d updates\n" "$numpkgs"
	printf "AUR: %d\n" "$numpkgs"
fi

printf "#ff8000\n"
if [ -n "$BLOCK_BUTTON" ]
then
	notify-send -i "system-software-update" "AUR updates" "$pkgs"
fi
