live_config_reload = false

[bell]
animation = "EaseOutExpo"
duration = 100

[bell.command]
program = "beep"
args = ["-f", "750", "-l", "100"]

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#818383"
blue = "#5833ff"
cyan = "#14f0f0"
green = "#31e722"
magenta = "#f935f8"
red = "#fc391f"
white = "#e9ebeb"
yellow = "#eaec23"

[colors.normal]
black = "#000000"
blue = "#492de1"
cyan = "#33bbc8"
green = "#25bc24"
magenta = "#d338d3"
red = "#c23621"
white = "#cbcccd"
yellow = "#adad27"

[colors.primary]
background = "#2a2a2a"
foreground = "#e9ebeb"

[font]
size = 9

[font.normal]
family = "monospace"

[font.offset]
y = 1

[window.dimensions]
columns = 80
lines = 24
